<div id="content-wapper-main">
		    <div id="content-wapper">
			    <div id="left-news">
	<div class="pathway-news">
      			<div itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><a href="http://www.peacetour.com.vn/" itemprop="url" class="homepage"><span itemprop="title">Trang chủ</span></a></div>
      			
     			<div itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb" class="no-bg"><a href="http://www.peacetour.com.vn/thu-tuc-visa.html#" itemprop="url" class="homepage"><span itemprop="title">THỦ TỤC VISA</span></a></div>
         
      
	</div>
			
	
		<div class="sub-left">	
			
		
			
			
				
				
		<div class="item0"><p class="img0"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-ukraina-1663.html"><img src="./Thủ tục Visa   Du lịch Hòa Bình_files/1385547073.jpg" width="300" alt=" Visa nhập cảnh Ukraina"> </a></p><div class="info-text"><p class="name"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-ukraina-1663.html"> Visa nhập cảnh Ukraina</a></p><p class="date">Cập nhật ngày: 27/11/2013</p><p class="summary">
									
								 </p></div></div>	
		
		<ul class="list-items">
			
			<li><p class="img"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-viet-nam-1475.html"><img src="./Thủ tục Visa   Du lịch Hòa Bình_files/1383300496.jpg" width="180" alt="Visa nhập cảnh Việt Nam"></a></p><div class="info-items"><p class="name"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-viet-nam-1475.html">Visa nhập cảnh Việt Nam</a></p><p class="date-timer">Cập nhật ngày: 01/11/2013</p><summary>
										
									</summary></div></li><li><p class="img"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-hoa-ky-1474.html"><img src="./Thủ tục Visa   Du lịch Hòa Bình_files/1383300493.jpg" width="180" alt="Visa nhập cảnh Hoa Kỳ"></a></p><div class="info-items"><p class="name"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-hoa-ky-1474.html">Visa nhập cảnh Hoa Kỳ</a></p><p class="date-timer">Cập nhật ngày: 01/11/2013</p><summary>
										
									</summary></div></li><li><p class="img"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-uc-1473.html"><img src="./Thủ tục Visa   Du lịch Hòa Bình_files/1383300477.jpg" width="180" alt="Visa nhập cảnh Úc"></a></p><div class="info-items"><p class="name"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-uc-1473.html">Visa nhập cảnh Úc</a></p><p class="date-timer">Cập nhật ngày: 01/11/2013</p><summary>
										
									</summary></div></li><li><p class="img"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-chau-au-1472.html"><img src="./Thủ tục Visa   Du lịch Hòa Bình_files/1383300472.jpg" width="180" alt="Visa nhập cảnh Châu Âu"></a></p><div class="info-items"><p class="name"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-chau-au-1472.html">Visa nhập cảnh Châu Âu</a></p><p class="date-timer">Cập nhật ngày: 01/11/2013</p><summary>
										
									</summary></div></li><li><p class="img"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-phap-1471.html"><img src="./Thủ tục Visa   Du lịch Hòa Bình_files/1383300467.jpg" width="180" alt="Visa nhập cảnh Pháp"></a></p><div class="info-items"><p class="name"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-phap-1471.html">Visa nhập cảnh Pháp</a></p><p class="date-timer">Cập nhật ngày: 01/11/2013</p><summary>
										
									</summary></div></li><li><p class="img"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-anh-quoc-1470.html"><img src="./Thủ tục Visa   Du lịch Hòa Bình_files/1383300461.jpg" width="180" alt="Visa nhập cảnh Anh Quốc"></a></p><div class="info-items"><p class="name"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-anh-quoc-1470.html">Visa nhập cảnh Anh Quốc</a></p><p class="date-timer">Cập nhật ngày: 01/11/2013</p><summary>
										
									</summary></div></li><li><p class="img"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-nhat-ban-1469.html"><img src="./Thủ tục Visa   Du lịch Hòa Bình_files/1383300458.jpg" width="180" alt="Visa nhập cảnh Nhật Bản"></a></p><div class="info-items"><p class="name"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-nhat-ban-1469.html">Visa nhập cảnh Nhật Bản</a></p><p class="date-timer">Cập nhật ngày: 01/11/2013</p><summary>
										
									</summary></div></li><li><p class="img"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-han-quoc-1468.html"><img src="./Thủ tục Visa   Du lịch Hòa Bình_files/1383300453.jpg" width="180" alt="Visa nhập cảnh Hàn Quốc "></a></p><div class="info-items"><p class="name"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-han-quoc-1468.html">Visa nhập cảnh Hàn Quốc </a></p><p class="date-timer">Cập nhật ngày: 01/11/2013</p><summary>
										
									</summary></div></li><li><p class="img"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-trung-quoc-1467.html"><img src="./Thủ tục Visa   Du lịch Hòa Bình_files/1383300434.jpg" width="180" alt="Visa nhập cảnh Trung Quốc"></a></p><div class="info-items"><p class="name"><a href="http://www.peacetour.com.vn/xem-tin/thu-tuc-visa-0/visa-nhap-canh-trung-quoc-1467.html">Visa nhập cảnh Trung Quốc</a></p><p class="date-timer">Cập nhật ngày: 01/11/2013</p><summary>
										
									</summary></div></li>			
			
			
		</ul>
		<!-- phan trang -->
		<div class="pages"><span class="pagebar-mainbody">&nbsp;<span class="pagebar-selections"><span class="pagelink-current">1</span></span>&nbsp;<a href="http://www.peacetour.com.vn/thu-tuc-visa/10">2</a>&nbsp;<a href="http://www.peacetour.com.vn/thu-tuc-visa/10"><div class="next">&nbsp;</div></a>&nbsp;</span></div>
	</div>
	
	</div>
<div id="right-news">
        
            
        
    <div class="group-photo">
                
            
        <link rel="stylesheet" type="text/css" href="./Thủ tục Visa   Du lịch Hòa Bình_files/album_news.css">
        <script type="text/javascript" src="./Thủ tục Visa   Du lịch Hòa Bình_files/slideshow.js" charset="UTF-8"></script>
        
        <div id="wrapper">
            <div class="title">
                <p class="text">Album Ảnh đẹp</p>
                <span class="text">&nbsp;</span>
            </div>
            
             <a href="javascript:;" class="next1" id="next2"></a>
             <a href="javascript:;" class="pre" id="prev2"></a>
            <div id="topnew_slideshow">
                 
                                 <div id="topnew_slideshow_1" class="topnew_slideshow">
                    <div class="img">
                       <a href="javascript:show_albums(114);" title="HÌnh ảnh Visa"><img src="./Thủ tục Visa   Du lịch Hòa Bình_files/1376418795.jpg" alt="HÌnh ảnh Visa" width="298"></a>
                    </div>
                    <h3><a href="javascript:show_albums(114);" title="HÌnh ảnh Visa">HÌnh ảnh Visa</a></h3>
                </div> 
                            </div>
        </div>
        
        
         <script type="text/javascript">
             $('#topnew_slideshow').cycle({ 
                    fx:'fade',        
                    speed: 1000, 
                    pause:   1,
                    speed:   300,
                    timeout: 5000,
                    next:   '#next2', 
                    prev:   '#prev2' 
                    });
              
             function show_albums(id){
                $.post(base_url + "api/showAlbums",{'albumid':id},function(data){                    
                    $("#show_albums").show();
                    $("#background_photo").show();
                    $("#show_albums").html(data);
                });
             }
             

        </script>
        
           <!--  album  -->
            <div id="show_albums" style="display: none;"></div>
            <div id="background_photo" style="display: none;">&nbsp;</div>
            </div>
    
    <div class="ads-news-r">
        <ul class="items-ads">
                    </ul>
    
    </div>
    
    
    <div class="box-online">
        <p class="title">&nbsp; LIÊN KẾT WEBSITE</p>
        <div class="box-content">
            <select name="" style="width: 99%;height: 30px;" onchange="window.open(this.value,&#39;_blank&#39;);">
	<option value="">|- Chọn liên kết website</option>
        <option value="http://www.hoabinhrachgiaresort.com.vn/">|- Hoa Binh Rach Gia Resort</option>
        <option value="http://hoabinhphuquoc.com.vn/">|- Hoa Binh Phu Quoc Resort</option>
    </select>   

        </div>
    </div>
    
    <div class="box-online">
        <p class="title">&nbsp; THỐNG KÊ TRUY CẬP</p>
        <div class="box-content">                    
            <div align="center">
</div> 
<table style="width: 100%;">
    <tbody><tr>
        <td style="width: 20px;"><img src="./Thủ tục Visa   Du lịch Hòa Bình_files/vall.png" alt=""></td>
        <td>Trực tuyến</td>
        <td class="cufon" align="right">5</td>
    </tr>
    <tr>
        <td><img src="./Thủ tục Visa   Du lịch Hòa Bình_files/vtoday.png" alt=""></td> 
        <td>Hôm nay</td>
        <td align="right" class="cufon">860</td>
    </tr>
    <tr>
        <td><img src="./Thủ tục Visa   Du lịch Hòa Bình_files/vmonth.png" alt=""></td>
        <td>Trong tháng</td>
        <td align="right" class="cufon">7581</td>
    </tr>
    <tr>
        <td><img src="./Thủ tục Visa   Du lịch Hòa Bình_files/vweek.png" alt=""></td>
        <td>Tổng truy cập</td>
        <td align="right" class="cufon">755022</td>
    </tr>    
</tbody></table>
    
        </div>
    </div>
    
</div>					
</div>
	
		
		